// Generated by build: npm run vercel-build
// This placeholder is overwritten during Vercel deployment
module.exports = async (req, res) => {
  res.status(503).json({ message: "Build in progress" });
};
